name: Workflow for checking a C calculator with Mayhem
on: [pull_request]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Make and run tests
        run: make tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          flags: unit-tests
          gcov_include: calculator.c

      - name: Quick Mayhem property checking and coverage testing
        uses: ForAllSecure/mcode-action@v1
        with:
          mayhem-url: ${{ secrets.MAYHEM_URL }}
          mayhem-token: ${{ secrets.MAYHEM_TOKEN }}
          args: --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }} --file Mayhemfile.calculator --duration 60
          sarif-output: sarif
          junit-output: junit
          coverage-output: coverage

      - name: Upload Mayhem SARIF security file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif

      - name: Upload JUNIT files created by Mayhem
        uses: actions/upload-artifact@v3
        with:
          name: junit
          path: junit

      - name: Upload Mayhem coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/*.lcov
          flags: vulnerability-tests
          name: mayhem
